BEGIN;

ALTER TABLE clinic.hardware_measurement_events
  ADD COLUMN IF NOT EXISTS payload_hash varchar(64),
  ADD COLUMN IF NOT EXISTS measurement_session_id uuid,
  ADD COLUMN IF NOT EXISTS print_requested_by_user_id integer
    REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS print_last_manual_reprint_at timestamptz,
  ADD COLUMN IF NOT EXISTS print_manual_reprint_count integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS clinic.hardware_event_audit (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(80) NOT NULL,
  result varchar(20) NOT NULL
    CHECK (result IN ('accepted', 'duplicate', 'rejected', 'published', 'failed', 'requested')),
  device_id varchar(80),
  request_id varchar(100),
  measurement_session_id uuid,
  message_id varchar(100),
  print_job_id varchar(100),
  actor_user_id integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  error_code varchar(100),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hardware_event_audit_request_idx
  ON clinic.hardware_event_audit (request_id, created_at DESC)
  WHERE request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS hardware_event_audit_session_idx
  ON clinic.hardware_event_audit (measurement_session_id, created_at DESC)
  WHERE measurement_session_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS hardware_event_audit_message_idx
  ON clinic.hardware_event_audit (message_id, created_at DESC)
  WHERE message_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS hardware_event_audit_print_job_idx
  ON clinic.hardware_event_audit (print_job_id, created_at DESC)
  WHERE print_job_id IS NOT NULL;

DROP INDEX IF EXISTS clinic.hardware_measurement_events_print_retry_idx;
CREATE INDEX hardware_measurement_events_print_retry_idx
  ON clinic.hardware_measurement_events (print_next_attempt_at, created_at)
  WHERE print_retryable = true
    AND print_status IN ('pending', 'requested', 'failed');

DO $runtime$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cliniccare_runtime') THEN
    GRANT SELECT, INSERT, UPDATE
      ON clinic.hardware_measurement_events TO cliniccare_runtime;
    GRANT SELECT, INSERT
      ON clinic.hardware_event_audit TO cliniccare_runtime;
    GRANT USAGE, SELECT
      ON SEQUENCE clinic.hardware_event_audit_audit_id_seq TO cliniccare_runtime;

    ALTER TABLE clinic.hardware_event_audit ENABLE ROW LEVEL SECURITY;
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'clinic'
        AND tablename = 'hardware_event_audit'
        AND policyname = 'cliniccare_runtime_backend_access'
    ) THEN
      CREATE POLICY cliniccare_runtime_backend_access
        ON clinic.hardware_event_audit
        FOR ALL TO cliniccare_runtime
        USING (true) WITH CHECK (true);
    END IF;
  END IF;
END
$runtime$;

COMMIT;
