-- Complete ClinicCare schema for a NEW, EMPTY database. Run once as owner.
-- Existing databases: use npm run migrate; never run this entire file again.
-- Backend tools read only the named sections below, not the complete schema.

BEGIN;

CREATE SCHEMA IF NOT EXISTS clinic;
SET search_path TO clinic, public;


DO $enum$
BEGIN
  CREATE TYPE clinic.user_role AS ENUM
    ('super_admin', 'admin', 'doctor', 'assistant', 'user');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$enum$;

DO $enum$
BEGIN
  CREATE TYPE clinic.slot_status AS ENUM ('open', 'locked', 'closed');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$enum$;

DO $enum$
BEGIN
  CREATE TYPE clinic.queue_source AS ENUM ('kiosk', 'online', 'staff');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$enum$;

DO $enum$
BEGIN
  CREATE TYPE clinic.queue_status AS ENUM
    ('waiting', 'called', 'skipped', 'served', 'cancelled', 'no_show');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$enum$;

DO $enum$
BEGIN
  CREATE TYPE clinic.record_visibility AS ENUM ('private', 'shared');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$enum$;

DO $enum$
BEGIN
  CREATE TYPE public.record_visibility AS ENUM ('private', 'team', 'public');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$enum$;

CREATE TABLE clinic.users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) UNIQUE,
  email varchar(60) UNIQUE,
  password_hash text,
  role clinic.user_role NOT NULL DEFAULT 'user',
  google_id varchar(50) UNIQUE,
  line_id varchar(50) UNIQUE,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  last_login_at timestamp,
  account_status varchar(32) NOT NULL DEFAULT 'active',
  email_verified_at timestamptz,
  profile_completed_at timestamptz,
  medical_consent_at timestamptz,
  medical_consent_version text,
  registration_source varchar(32) NOT NULL DEFAULT 'local',
  status_reason text,
  status_changed_at timestamptz,
  status_changed_by integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  deactivated_at timestamptz,
  session_version integer NOT NULL DEFAULT 1,
  CONSTRAINT users_email_format_chk CHECK
    (email IS NULL OR email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  CONSTRAINT users_account_status_chk CHECK
    (account_status IN ('active', 'pending_verification', 'deactivated',
                        'suspended', 'duplicate', 'unclaimed')),
  CONSTRAINT users_identity_chk CHECK
    (username IS NOT NULL OR email IS NOT NULL OR google_id IS NOT NULL OR line_id IS NOT NULL),
  CONSTRAINT users_auth_chk CHECK
    (password_hash IS NOT NULL OR google_id IS NOT NULL OR line_id IS NOT NULL
      OR (account_status = 'unclaimed' AND registration_source = 'walkin'))
);

CREATE TABLE clinic.provinces (
  province_code varchar(10) PRIMARY KEY,
  name_th varchar(50) NOT NULL,
  name_en varchar(50),
  region varchar(50),
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clinic.user_details (
  detail_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES clinic.users(user_id) ON DELETE CASCADE,
  national_id varchar(20),
  first_name varchar(100),
  last_name varchar(100),
  birth_date date,
  profile_image text,
  profile_image_drive_id text,
  gender varchar(20),
  blood_type varchar(2),
  address text,
  province_code varchar(10) REFERENCES clinic.provinces(province_code)
    ON UPDATE CASCADE ON DELETE SET NULL,
  ethnicity varchar(10),
  nationality varchar(10),
  phone varchar(10),
  emergency_phone varchar(10),
  email varchar(50),
  congenital_disease text,
  drug_allergy text,
  food_allergy text,
  position text,
  license_no varchar(50),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  title varchar(20),
  patient_code text GENERATED ALWAYS AS (lpad(user_id::text, 3, '0')) STORED,
  CONSTRAINT user_details_email_format_chk CHECK
    (email IS NULL OR email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

CREATE INDEX user_details_profile_image_drive_idx
  ON clinic.user_details(profile_image_drive_id)
  WHERE profile_image_drive_id IS NOT NULL;

CREATE TABLE clinic.profile_image_cleanup (
  drive_file_id text PRIMARY KEY,
  folder_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0
);
REVOKE ALL ON clinic.profile_image_cleanup FROM PUBLIC;

CREATE UNIQUE INDEX user_details_national_id_unique_idx
  ON clinic.user_details (national_id)
  WHERE national_id IS NOT NULL AND btrim(national_id) <> '';
CREATE INDEX user_details_phone_idx ON clinic.user_details (phone);

CREATE TABLE clinic.email_verification_otps (
  verification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES clinic.users(user_id) ON DELETE CASCADE,
  token_hash varchar(64) NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  last_sent_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX email_verification_user_active_idx
  ON clinic.email_verification_otps (user_id, expires_at DESC)
  WHERE used_at IS NULL;

CREATE TABLE clinic.password_reset_otps (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(100) NOT NULL,
  otp varchar(6),
  otp_hash varchar(64),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  verified_at timestamptz,
  used_at timestamptz,
  token text NOT NULL,
  expires_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX password_reset_otps_email_idx
  ON clinic.password_reset_otps (lower(email), expires_at DESC);

CREATE TABLE clinic.password_resets (
  reset_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES clinic.users(user_id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  expires_at timestamp NOT NULL,
  used boolean NOT NULL DEFAULT false,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE clinic.appointment_slot_templates (
  template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  avaliable_date varchar(20) NOT NULL,
  hour_of_day smallint NOT NULL,
  UNIQUE (avaliable_date, hour_of_day),
  CONSTRAINT slot_template_period_chk CHECK
    ((avaliable_date = 'morning' AND hour_of_day BETWEEN 7 AND 10)
      OR (avaliable_date = 'afternoon' AND hour_of_day BETWEEN 16 AND 20))
);

CREATE TABLE clinic.appointment_slots (
  slot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_date date NOT NULL,
  avaliable_date varchar(20) NOT NULL,
  hour_of_day smallint NOT NULL,
  template_id integer REFERENCES clinic.appointment_slot_templates(template_id),
  notes text,
  status clinic.slot_status NOT NULL DEFAULT 'open',
  start_ts timestamp GENERATED ALWAYS AS
    (service_date::timestamp + make_interval(hours => hour_of_day::integer)) STORED,
  bookable_until timestamp GENERATED ALWAYS AS
    (service_date::timestamp + make_interval(hours => hour_of_day::integer)
      + interval '30 minutes') STORED,
  UNIQUE (service_date, avaliable_date, hour_of_day),
  CONSTRAINT appointment_slot_period_chk CHECK
    ((avaliable_date = 'morning' AND hour_of_day BETWEEN 7 AND 10)
      OR (avaliable_date = 'afternoon' AND hour_of_day BETWEEN 16 AND 20))
);

CREATE INDEX appointment_slots_date_status_idx
  ON clinic.appointment_slots (service_date, status);

CREATE TABLE clinic.appointments (
  appointment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES clinic.users(user_id) ON DELETE CASCADE,
  slot_id integer NOT NULL REFERENCES clinic.appointment_slots(slot_id) ON DELETE RESTRICT,
  status varchar(20) NOT NULL DEFAULT 'pending',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  action_taken boolean DEFAULT false,
  description text,
  service_type varchar(100),
  cancellation_reason text,
  CONSTRAINT appointments_status_chk CHECK
    (status IN ('pending', 'approved', 'rejected', 'cancelled', 'completed', 'no_show'))
);

CREATE UNIQUE INDEX appointments_active_slot_id_key
  ON clinic.appointments (slot_id)
  WHERE status NOT IN ('cancelled', 'rejected');
CREATE INDEX appointments_user_created_idx
  ON clinic.appointments (user_id, created_at DESC);

CREATE TABLE clinic.queue_tickets (
  queue_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_number varchar(20) NOT NULL,
  prefix char(1) NOT NULL DEFAULT 'B',
  numeric_no integer NOT NULL,
  service_date date NOT NULL DEFAULT CURRENT_DATE,
  avaliable_date varchar(20) NOT NULL,
  source clinic.queue_source NOT NULL,
  appointment_id integer REFERENCES clinic.appointments(appointment_id),
  user_id integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  service_type varchar(50),
  status clinic.queue_status NOT NULL DEFAULT 'waiting',
  issued_at timestamp DEFAULT CURRENT_TIMESTAMP,
  called_at timestamp,
  served_at timestamp,
  skipped_at timestamp,
  window_id varchar(20),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT queue_ticket_source_chk CHECK
    ((source = 'online' AND appointment_id IS NOT NULL) OR source <> 'online')
);

CREATE UNIQUE INDEX queue_tickets_service_date_queue_number_key
  ON clinic.queue_tickets (service_date, queue_number)
  WHERE status <> 'cancelled';
CREATE INDEX queue_tickets_date_status_idx
  ON clinic.queue_tickets (service_date, status, numeric_no);
CREATE INDEX queue_tickets_user_idx ON clinic.queue_tickets (user_id);

CREATE TABLE clinic.appointment_access_codes (
  access_code_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id integer NOT NULL UNIQUE
    REFERENCES clinic.appointments(appointment_id) ON DELETE CASCADE,
  queue_id integer NOT NULL UNIQUE
    REFERENCES clinic.queue_tickets(queue_id) ON DELETE CASCADE,
  code_hash varchar(64) NOT NULL UNIQUE,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '15 minutes'),
  issued_by integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  issue_reason varchar(80),
  code_ciphertext text
);

CREATE INDEX appointment_access_codes_unused_idx
  ON clinic.appointment_access_codes (code_hash) WHERE used_at IS NULL;
CREATE INDEX appointment_access_codes_expires_at_idx
  ON clinic.appointment_access_codes (expires_at) WHERE used_at IS NULL;

CREATE TABLE clinic.patient_checkins (
  checkin_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id integer NOT NULL UNIQUE
    REFERENCES clinic.appointments(appointment_id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES clinic.users(user_id),
  verified_by_user_id integer NOT NULL REFERENCES clinic.users(user_id),
  verification_method varchar(80) NOT NULL,
  verification_note text,
  verified_at timestamptz NOT NULL DEFAULT now(),
  code_issued_at timestamptz,
  code_expires_at timestamptz,
  reason varchar(80) NOT NULL DEFAULT 'forgot_email',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE clinic.measurements (
  measurement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_number varchar(20) NOT NULL,
  weight numeric(5,2),
  height numeric(5,2),
  bmi numeric(5,2),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  queue_id integer REFERENCES clinic.queue_tickets(queue_id) ON DELETE CASCADE,
  chief_complaint text,
  temperature numeric(4,1),
  heart_rate integer,
  respiratory_rate integer,
  systolic_bp integer,
  diastolic_bp integer,
  CONSTRAINT measurements_positive_chk CHECK
    ((weight IS NULL OR weight > 0) AND (height IS NULL OR height > 0)
      AND (temperature IS NULL OR temperature > 0))
);

CREATE INDEX measurements_queue_id_idx ON clinic.measurements (queue_id);

-- MQTT hardware integration. The backend calculates and persists BMI so every
-- consumer (web and printer) reads the same canonical value.
ALTER TABLE clinic.measurements
  ADD COLUMN source varchar(20) NOT NULL DEFAULT 'manual',
  ADD COLUMN device_id varchar(80),
  ADD COLUMN hardware_message_id varchar(100),
  ADD COLUMN measured_at timestamptz;

CREATE UNIQUE INDEX measurements_hardware_message_id_key
  ON clinic.measurements (hardware_message_id)
  WHERE hardware_message_id IS NOT NULL;

CREATE UNIQUE INDEX measurements_device_hardware_message_key
  ON clinic.measurements (device_id, hardware_message_id)
  WHERE device_id IS NOT NULL AND hardware_message_id IS NOT NULL;

CREATE TABLE clinic.hardware_otp_sessions (
  session_id uuid PRIMARY KEY,
  device_id varchar(80) NOT NULL,
  access_code_id bigint NOT NULL
    REFERENCES clinic.appointment_access_codes(access_code_id) ON DELETE CASCADE,
  queue_id integer NOT NULL
    REFERENCES clinic.queue_tickets(queue_id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX hardware_otp_sessions_active_idx
  ON clinic.hardware_otp_sessions (device_id, expires_at)
  WHERE used_at IS NULL;

CREATE TABLE clinic.hardware_measurement_events (
  message_id varchar(100) PRIMARY KEY,
  device_id varchar(80) NOT NULL,
  mode varchar(20) NOT NULL CHECK (mode IN ('online', 'walk_in')),
  queue_id integer NOT NULL
    REFERENCES clinic.queue_tickets(queue_id) ON DELETE CASCADE,
  measurement_id integer NOT NULL UNIQUE
    REFERENCES clinic.measurements(measurement_id) ON DELETE CASCADE,
  payload_hash varchar(64),
  measurement_session_id uuid,
  print_job_id varchar(100) UNIQUE,
  print_status varchar(20) NOT NULL DEFAULT 'pending'
    CHECK (print_status IN ('pending', 'requested', 'printed', 'failed')),
  print_attempts integer NOT NULL DEFAULT 0,
  print_error_code varchar(80),
  print_retryable boolean NOT NULL DEFAULT true,
  print_next_attempt_at timestamptz,
  print_last_failed_at timestamptz,
  print_requested_at timestamptz,
  print_requested_by_user_id integer
    REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  print_last_manual_reprint_at timestamptz,
  print_manual_reprint_count integer NOT NULL DEFAULT 0,
  printed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX hardware_measurement_events_pending_print_idx
  ON clinic.hardware_measurement_events (created_at)
  WHERE print_status IN ('pending', 'failed');

CREATE UNIQUE INDEX hardware_measurement_events_device_message_key
  ON clinic.hardware_measurement_events (device_id, message_id);

CREATE INDEX hardware_measurement_events_print_retry_idx
  ON clinic.hardware_measurement_events (print_next_attempt_at, created_at)
  WHERE print_retryable = true
    AND print_status IN ('pending', 'requested', 'failed');

-- BEGIN SECTION: measurement_ack_outbox
CREATE TABLE IF NOT EXISTS clinic.hardware_measurement_ack_outbox (
  message_id varchar(100) PRIMARY KEY
    REFERENCES clinic.hardware_measurement_events(message_id) ON DELETE CASCADE,
  device_id varchar(80) NOT NULL,
  ack_payload jsonb NOT NULL,
  published_at timestamptz,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  next_attempt_at timestamptz NOT NULL DEFAULT now() + interval '10 seconds',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hardware_measurement_ack_outbox_pending_idx
  ON clinic.hardware_measurement_ack_outbox (next_attempt_at, created_at)
  WHERE published_at IS NULL;

DO $runtime$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cliniccare_runtime') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE
      ON clinic.hardware_measurement_ack_outbox TO cliniccare_runtime;
    ALTER TABLE clinic.hardware_measurement_ack_outbox ENABLE ROW LEVEL SECURITY;
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'clinic'
        AND tablename = 'hardware_measurement_ack_outbox'
        AND policyname = 'cliniccare_runtime_backend_full_access'
    ) THEN
      CREATE POLICY cliniccare_runtime_backend_full_access
        ON clinic.hardware_measurement_ack_outbox
        FOR ALL TO cliniccare_runtime
        USING (true) WITH CHECK (true);
    END IF;
  END IF;
END
$runtime$;
-- END SECTION: measurement_ack_outbox

CREATE TABLE clinic.hardware_event_audit (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(80) NOT NULL,
  result varchar(20) NOT NULL
    CHECK (result IN ('accepted', 'duplicate', 'rejected', 'published', 'failed', 'requested')),
  device_id varchar(80),
  request_id varchar(100),
  measurement_session_id uuid,
  message_id varchar(100),
  print_job_id varchar(100),
  actor_user_id integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  error_code varchar(100),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX hardware_event_audit_request_idx
  ON clinic.hardware_event_audit (request_id, created_at DESC)
  WHERE request_id IS NOT NULL;
CREATE INDEX hardware_event_audit_session_idx
  ON clinic.hardware_event_audit (measurement_session_id, created_at DESC)
  WHERE measurement_session_id IS NOT NULL;
CREATE INDEX hardware_event_audit_message_idx
  ON clinic.hardware_event_audit (message_id, created_at DESC)
  WHERE message_id IS NOT NULL;
CREATE INDEX hardware_event_audit_print_job_idx
  ON clinic.hardware_event_audit (print_job_id, created_at DESC)
  WHERE print_job_id IS NOT NULL;

CREATE TABLE clinic.medical_records (
  record_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES clinic.users(user_id) ON DELETE CASCADE,
  visit_date timestamp NOT NULL,
  symptoms text,
  diagnosis text,
  treatment text,
  medications jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  doctor_id integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  follow_up_date date,
  visibility public.record_visibility NOT NULL DEFAULT 'private',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  body_drawing_data text
);

CREATE INDEX medical_records_user_visit_idx
  ON clinic.medical_records (user_id, visit_date DESC);

CREATE TABLE clinic.user_feedbacks (
  feedback_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  score integer CHECK (score BETWEEN 1 AND 5),
  liked boolean,
  category text,
  comment text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  record_id integer REFERENCES clinic.medical_records(record_id) ON DELETE SET NULL,
  visit_date date,
  service_type text
);

CREATE UNIQUE INDEX user_feedbacks_user_record_unique
  ON clinic.user_feedbacks (user_id, record_id) WHERE record_id IS NOT NULL;

CREATE TABLE clinic.help_requests (
  help_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  category text,
  tags text[],
  visibility clinic.record_visibility NOT NULL DEFAULT 'private',
  view_count integer DEFAULT 0 CHECK (view_count >= 0),
  related_feedback_id integer REFERENCES clinic.user_feedbacks(feedback_id) ON DELETE SET NULL,
  request_status varchar(24) NOT NULL DEFAULT 'pending',
  reviewed_by integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  review_note text,
  verification_method varchar(80),
  CONSTRAINT help_request_status_chk CHECK
    (request_status IN ('pending', 'approved', 'rejected', 'resolved'))
);

CREATE TABLE clinic.user_notifications (
  notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES clinic.users(user_id) ON DELETE CASCADE,
  source_type varchar(40) NOT NULL,
  source_id text NOT NULL,
  event_key varchar(80) NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  severity varchar(20) NOT NULL DEFAULT 'info',
  target_url text,
  event_at timestamptz,
  email_required boolean NOT NULL DEFAULT false,
  email_sent_at timestamptz,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '1 month'),
  UNIQUE (user_id, source_type, source_id, event_key),
  CONSTRAINT notification_severity_chk CHECK
    (severity IN ('info', 'success', 'warning', 'error'))
);

CREATE INDEX user_notifications_user_active_idx
  ON clinic.user_notifications (user_id, is_read, created_at DESC);
CREATE INDEX user_notifications_expiry_idx
  ON clinic.user_notifications (expires_at);

CREATE TABLE clinic.clinic_holidays (
  service_date date NOT NULL,
  avaliable_date varchar(20) NOT NULL DEFAULT 'all_day',
  reason text,
  created_by integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (service_date, avaliable_date),
  CONSTRAINT clinic_holiday_period_chk CHECK
    (avaliable_date IN ('morning', 'afternoon', 'all_day'))
);

CREATE INDEX clinic_holidays_date_idx ON clinic.clinic_holidays (service_date);

CREATE TABLE clinic.clinic_open_days (
  service_date date PRIMARY KEY,
  reason text,
  created_by integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE clinic.weekly_closed_windows (
  weekday smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  avaliable_date varchar(20) NOT NULL,
  is_closed boolean NOT NULL DEFAULT false,
  reason text,
  PRIMARY KEY (weekday, avaliable_date),
  CONSTRAINT weekly_closed_period_chk CHECK
    (avaliable_date IN ('morning', 'afternoon'))
);

CREATE TABLE clinic.advance_booking_weeks (
  week_start date PRIMARY KEY,
  week_end date NOT NULL,
  created_by integer REFERENCES clinic.users(user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT advance_booking_weeks_valid_range CHECK (week_end >= week_start),
  CONSTRAINT advance_booking_weeks_same_month CHECK
    (date_trunc('month', week_start::timestamp) = date_trunc('month', week_end::timestamp))
);

CREATE TABLE clinic.audit_logs (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL,
  actor_user_id integer,
  actor_role varchar(32),
  action varchar(160) NOT NULL,
  entity_type varchar(80),
  entity_id varchar(100),
  result varchar(20) NOT NULL,
  http_method varchar(10) NOT NULL,
  route text NOT NULL,
  status_code integer NOT NULL,
  ip_address inet,
  user_agent text,
  error_code varchar(100),
  duration_ms integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_result_chk CHECK (result IN ('success', 'denied', 'error'))
);

CREATE INDEX audit_logs_created_id_idx
  ON clinic.audit_logs (created_at DESC, audit_id DESC);
CREATE INDEX audit_logs_actor_idx
  ON clinic.audit_logs (actor_user_id, created_at DESC);

CREATE OR REPLACE VIEW clinic.staff_profiles AS
SELECT u.user_id, u.role, d.first_name, d.last_name, d.position, d.license_no, d.phone
FROM clinic.users u
LEFT JOIN clinic.user_details d ON d.user_id = u.user_id
WHERE u.role IN ('super_admin', 'admin', 'doctor', 'assistant');

CREATE OR REPLACE VIEW clinic.faqs_public AS
SELECT help_id AS faq_id, title AS question, description AS answer,
       category, tags, updated_at
FROM clinic.help_requests
WHERE visibility = 'shared' AND request_status IN ('approved', 'resolved');

CREATE OR REPLACE VIEW clinic.slots_status_today AS
SELECT s.slot_id, s.service_date, s.avaliable_date, s.hour_of_day, s.status,
       s.start_ts, s.bookable_until,
       NOT EXISTS (
         SELECT 1 FROM clinic.appointments a
         WHERE a.slot_id = s.slot_id AND a.status NOT IN ('cancelled', 'rejected')
       ) AS is_empty,
       (s.status = 'open' AND now() <= s.bookable_until) AS is_bookable
FROM clinic.appointment_slots s
WHERE s.service_date = CURRENT_DATE;

CREATE OR REPLACE VIEW clinic.calendar_this_week AS
SELECT s.service_date AS date,
       count(*)::integer AS total_slots,
       count(a.appointment_id) FILTER
         (WHERE a.status NOT IN ('cancelled', 'rejected'))::integer AS booked_slots,
       (count(*) - count(a.appointment_id) FILTER
         (WHERE a.status NOT IN ('cancelled', 'rejected')))::integer AS available_slots,
       CASE WHEN bool_and(s.status = 'closed') THEN 'closed' ELSE 'open' END AS status
FROM clinic.appointment_slots s
LEFT JOIN clinic.appointments a ON a.slot_id = s.slot_id
WHERE s.service_date BETWEEN date_trunc('week', CURRENT_DATE)::date
                         AND (date_trunc('week', CURRENT_DATE)::date + 6)
GROUP BY s.service_date;

-- Initial time-slot templates used by the current backend.
INSERT INTO clinic.appointment_slot_templates (avaliable_date, hour_of_day)
VALUES ('morning', 7), ('morning', 8), ('morning', 9), ('morning', 10),
       ('afternoon', 16), ('afternoon', 17), ('afternoon', 18),
       ('afternoon', 19), ('afternoon', 20)
ON CONFLICT DO NOTHING;

-- BEGIN SECTION: runtime_functions
CREATE OR REPLACE FUNCTION clinic.seed_slots(start_date date, end_date date)
RETURNS void AS $$
BEGIN
  IF start_date IS NULL OR end_date IS NULL OR end_date < start_date THEN
    RAISE EXCEPTION 'Invalid slot date range';
  END IF;

  INSERT INTO clinic.appointment_slots
    (service_date, avaliable_date, hour_of_day, status)
  SELECT d.service_date::date, h.avaliable_date, h.hour_of_day,
         'open'::clinic.slot_status
  FROM generate_series(start_date, end_date, interval '1 day') d(service_date)
  CROSS JOIN (VALUES
    ('morning'::varchar, 7::smallint), ('morning'::varchar, 8::smallint),
    ('morning'::varchar, 9::smallint), ('morning'::varchar, 10::smallint),
    ('afternoon'::varchar, 16::smallint), ('afternoon'::varchar, 17::smallint),
    ('afternoon'::varchar, 18::smallint), ('afternoon'::varchar, 19::smallint)
  ) h(avaliable_date, hour_of_day)
  ON CONFLICT (service_date, avaliable_date, hour_of_day) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION clinic.lock_timed_out_slots()
RETURNS void AS $$
BEGIN
  UPDATE clinic.appointment_slots s
  SET status = 'locked'
  WHERE s.status = 'open'
    AND s.bookable_until < (now() AT TIME ZONE 'Asia/Bangkok')
    AND NOT EXISTS (
      SELECT 1 FROM clinic.appointments a
      WHERE a.slot_id = s.slot_id
        AND a.status NOT IN ('cancelled', 'rejected')
    );
END;
$$ LANGUAGE plpgsql;
-- END SECTION: runtime_functions

-- BEGIN SECTION: runtime_grants
DO $runtime$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cliniccare_runtime') THEN
    GRANT SELECT, INSERT, UPDATE
      ON clinic.hardware_measurement_events TO cliniccare_runtime;
    GRANT SELECT, INSERT
      ON clinic.hardware_event_audit TO cliniccare_runtime;
    GRANT USAGE, SELECT
      ON SEQUENCE clinic.hardware_event_audit_audit_id_seq TO cliniccare_runtime;

    ALTER TABLE clinic.hardware_event_audit ENABLE ROW LEVEL SECURITY;
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'clinic'
        AND tablename = 'hardware_event_audit'
        AND policyname = 'cliniccare_runtime_backend_access'
    ) THEN
      CREATE POLICY cliniccare_runtime_backend_access
        ON clinic.hardware_event_audit
        FOR ALL TO cliniccare_runtime
        USING (true) WITH CHECK (true);
    END IF;
  END IF;
END
$runtime$;

DO $grants$
DECLARE
  target_table text;
BEGIN
  -- Local installations need not create the production runtime role.
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cliniccare_runtime') THEN
    RAISE NOTICE 'Skipping runtime grants: cliniccare_runtime does not exist';
    RETURN;
  END IF;

  EXECUTE format('GRANT CONNECT ON DATABASE %I TO cliniccare_runtime', current_database());
  GRANT USAGE ON SCHEMA clinic TO cliniccare_runtime;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA clinic TO cliniccare_runtime;
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA clinic TO cliniccare_runtime;
  GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA clinic TO cliniccare_runtime;

  -- Run as the schema/migration owner so future objects receive these grants.
  ALTER DEFAULT PRIVILEGES IN SCHEMA clinic
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cliniccare_runtime;
  ALTER DEFAULT PRIVILEGES IN SCHEMA clinic
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cliniccare_runtime;
  ALTER DEFAULT PRIVILEGES IN SCHEMA clinic
    GRANT EXECUTE ON FUNCTIONS TO cliniccare_runtime;

  FOR target_table IN
    SELECT c.relname FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'clinic' AND c.relkind IN ('r', 'p')
  LOOP
    EXECUTE format('ALTER TABLE clinic.%I ENABLE ROW LEVEL SECURITY', target_table);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'clinic' AND tablename = target_table
        AND policyname = 'cliniccare_runtime_backend_full_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY cliniccare_runtime_backend_full_access ON clinic.%I
         FOR ALL TO cliniccare_runtime USING (true) WITH CHECK (true)', target_table);
    END IF;
  END LOOP;
END
$grants$;
-- END SECTION: runtime_grants

COMMIT;
